### ISSUE TITLE
One direction Scroll

### ISSUE THREAD

**Issue by aliakkawi** [0xCompany/roller_list#1]
Hi and thanks for the library, how can i make a one direction only scroll? instead of random direction.
Thanks

**Comment by Yahhi** [comment]
I think your task is related to creating a custom ScrollPhysics. This answer can help https://stackoverflow.com/questions/55502868/flutter-pageview-disable-left-or-right-side-scrolling
Then I have to add scroll physics as a parameter to the widget. 
You can create a PR with this functionality or wait a couple of days until I do it by myself

**Comment by aliakkawi** [comment]
Thanks a lot, i will be glad if you can add this feature.

**Comment by Yahhi** [comment]
The feature is added

**Comment by aliakkawi** [comment]
Thanks a lot, i appreciate.

**Comment by aliakkawi** [comment]
I set the ScrollType for the RollerList to ScrollType.goesOnlyBottom and they are still rolling in both direction.I think this is due to the random number for RotationTarget and the smoothScrollToIndex.

**Comment by Yahhi** [comment]
I lwanted to limit only user input direction. So the user could not scroll it wrong way.
By your comment it seems like you want to limit programmatical scroll too, isn't it?

**Comment by aliakkawi** [comment]
In my project i set enabled: false, and i only allow scrolling programatically by tapping a button.
